<?php
if ( !defined( 'ABSPATH' ) ) { exit; } // Exit if accessed directly.

class Zume_301_Redirects
{

    private static $_instance = null;
    public static function instance() {
        if ( is_null( self::$_instance ) ) {
            self::$_instance = new self();
        }
        return self::$_instance;
    }

    public function __construct() {
        if( dt_is_rest() ) {
            return;
        }

        if ( defined('DOING_CRON') && DOING_CRON ) {
            return;
        }

        $url = dt_get_url_path();
        if ( empty( $url ) ) {
            return;
        }

        $list = $this->list_of_urls();

        // dt_write_log('Zume_301_Redirects');
        // dt_write_log( $url );

        if ( isset( $list[$url] ) ) {
            $this->redirect( $list[$url] );
        }
    }

    public function list_of_urls() {
        $z = 'https://zume.training/';
        $l= 'https://legacy.zume.training/';

        $pages = [
            'about-am' => 'am/about',
            'about-ar_jo' => 'ar_jo/about',
            'about-ar' => 'ar/about',
            'about-asl' => 'asl/about',
            'about-bho' => 'bho/about',
            'about-bn' => 'bn/about',
            'about-bs' => 'bs/about',
            'about-de' => 'de/about',
            'about-es' => 'es/about',
            'about-es-es' => 'es/about',
            'about-fa' => 'fa/about',
            'about-fr' => 'fr/about',
            'about-gu' => 'gu/about',
            'about-ha' => 'ha/about',
            'about-hi' => 'hi/about',
            'about-hr' => 'hr/about',
            'about-in' => 'in/about',
            'about-it' => 'it/about',
            'about-ja' => 'ja/about',
            'about-kn' => 'kn/about',
            'about-ko' => 'ko/about',
            'about-ku' => 'ku/about',
            'about-lo' => 'lo/about',
            'about-mai' => 'mai/about',
            'about-ml' => 'ml/about',
            'about-mr' => 'mr/about',
            'about-or' => 'or/about',
            'about-pa' => 'pa/about',
            'about-pt' => 'pt/about',
            'about-ro' => 'ro/about',
            'about-ru' => 'ru/about',
            'about-sl' => 'sl/about',
            'about-so' => 'so/about',
            'about-sw' => 'sw/about',
            'about-ta' => 'ta/about',
            'about-te' => 'te/about',
            'about-th' => 'th/about',
            'about-tr' => 'tr/about',
            'about-ur' => 'ur/about',
            'about-vi' => 'vi/about',
            'about-yo' => 'yo/about',
            'about-zhcn' => 'zhcn/about',
            'about-zhhk' => 'zhhk/about',
            'about-zhtw' => 'zhtw/about',

            'vision-am' => 'am/training',
            'vision-ar_jo' => 'ar_jo/training',
            'vision-ar' => 'ar/training',
            'vision-asl' => 'asl/training',
            'vision-bho' => 'bho/training',
            'vision-bn' => 'bn/training',
            'vision-bs' => 'bs/training',
            'vision-casting-the-greatest-blessing-am' => '',
            'vision-casting-the-greatest-blessing-gu' => '',
            'vision-de' => 'de/training',
            'vision-es' => 'es/training',
            'vision-fa' => 'fa/training',
            'vision-fr' => 'fr/training',
            'vision-gu' => 'gu/training',
            'vision-ha' => 'ha/training',
            'vision-hi' => 'hi/training',
            'vision-hr' => 'hr/training',
            'vision-id' => 'id/training',
            'vision-it' => 'it/training',
            'vision-ja' => 'ja/training',
            'vision-kn' => 'kn/training',
            'vision-ko' => 'ko/training',
            'vision-ku' => 'ku/training',
            'vision-lo' => 'lo/training',
            'vision-mai' => 'mai/training',
            'vision-ml' => 'ml/training',
            'vision-mr' => 'mr/training',
            'vision-ne' => 'ne/training',
            'vision-or' => 'or/training',
            'vision-pa' => 'pa/training',
            'vision-ro' => 'ro/training',
            'vision-ru' => 'ru/training',
            'vision-sl' => 'sl/training',
            'vision-so' => 'so/training',
            'vision-swa' => 'swa/training',
            'vision-ta' => 'ta/training',
            'vision-te' => 'te/training',
            'vision-th' => 'th/training',
            'vision-tr' => 'tr/training',
            'vision-ur' => 'ur/training',
            'vision-vi' => 'vi/training',
            'vision-yo' => 'yo/training',
            'vision-zhcn' => 'zhcn/training',
            'vision-zhhk' => 'zhhk/training',
            'vision-zhtw' => 'zhtw/training',


            'course-am' => 'am/training',
            'course-ar_jo' => 'ar_jo/training',
            'course-ar' => 'ar/training',
            'course-asl' => 'asl/training',
            'course-bho' => 'bho/training',
            'course-bn' => 'bn/training',
            'course-bs' => 'bs/training',
            'course-de' => 'de/training',
            'course-es' => 'es/training',
            'course-fa' => 'fa/training',
            'course-fr' => 'fr/training',
            'course-gu' => 'gu/training',
            'course-ha' => 'ha/training',
            'course-hi' => 'hi/training',
            'course-hr' => 'hr/training',
            'course-id' => 'id/training',
            'course-it' => 'it/training',
            'course-ja' => 'ja/training',
            'course-kn' => 'kn/training',
            'course-ko' => 'ko/training',
            'course-ku' => 'ku/training',
            'course-lo' => 'lo/training',
            'course-mai' => 'mai/training',
            'course-ml' => 'ml/training',
            'course-mr' => 'mr/training',
            'course-ne' => 'ne/training',
            'course-or' => 'or/training',
            'course-pa' => 'pa/training',
            'course-pt' => 'pt/training',
            'course-ro' => 'ro/training',
            'course-ru' => 'ru/training',
            'course-sl' => 'sl/training',
            'course-so' => 'so/training',
            'course-sw' => 'sw/training',
            'course-ta' => 'ta/training',
            'course-te' => 'te/training',
            'course-th' => 'th/training',
            'course-tr' => 'tr/training',
            'course-ur' => 'ur/training',
            'course-vi' => 'vi/training',
            'course-yo' => 'yo/training',
            'course-zhcn' => 'zhcn/training',
            'course-zhhk' => 'zhhk/training',
            'course-zhtw' => 'zhtw/training',

            'dashboard-ar' => 'ar/dashboard',
            'dashboard-bn' => 'bn/dashboard',
            'dashboard-es' => 'es/dashboard',
            'dashboard-fa' => 'fa/dashboard',
            'dashboard-fr' => 'fr/dashboard',
            'dashboard-hi' => 'hi/dashboard',
            'dashboard-in' => 'in/dashboard',
            'dashboard-it' => 'it/dashboard',
            'dashboard-ku' => 'ku/dashboard',
            'dashboard-mr' => 'mr/dashboard',
            'dashboard-or' => 'or/dashboard',
            'dashboard-so' => 'so/dashboard',
            'dashboard-sw' => 'sw/dashboard',
            'dashboard-ta' => 'ta/dashboard',
            'dashboard-te' => 'te/dashboard',
            'dashboard-th' => 'th/dashboard',
            'dashboard-zhcn' => 'zhcn/dashboard',
            'dashboard-zhtw' => 'zhtw/dashboard',


            'faq-am' => 'am/about',
            'faq-ar_jo' => 'ar_jo/about',
            'faq-ar' => 'ar/about',
            'faq-asl' => 'asl/about',
            'faq-bho' => 'bho/about',
            'faq-bn' => 'bn/about',
            'faq-bs' => 'bs/about',
            'faq-de' => 'de/about',
            'faq-es' => 'es/about',
            'faq-fa' => 'fa/about',
            'faq-fr' => 'fr/about',
            'faq-gu' => 'gu/about',
            'faq-ha' => 'ha/about',
            'faq-hi' => 'hi/about',
            'faq-hr' => 'hr/about',
            'faq-in' => 'in/about',
            'faq-it' => 'it/about',
            'faq-ja' => 'ja/about',
            'faq-kn' => 'kn/about',
            'faq-ko' => 'ko/about',
            'faq-ku' => 'ku/about',
            'faq-lo' => 'lo/about',
            'faq-mai' => 'mai/about',
            'faq-ml' => 'ml/about',
            'faq-mr' => 'mr/about',
            'faq-ne' => 'ne/about',
            'faq-or' => 'or/about',
            'faq-pa' => 'pa/about',
            'faq-pt' => 'pt/about',
            'faq-ro' => 'ro/about',
            'faq-ru' => 'ru/about',
            'faq-sl' => 'sl/about',
            'faq-so' => 'so/about',
            'faq-sw' => 'sw/about',
            'faq-ta' => 'ta/about',
            'faq-te' => 'te/about',
            'faq-th' => 'th/about',
            'faq-tr' => 'tr/about',
            'faq-ur' => 'ur/about',
            'faq-vi' => 'vi/about',
            'faq-yo' => 'yo/about',
            'faq-zhcn' => 'zhcn/about',
            'faq-zhhk' => 'zhhk/about',
            'faq-zhtw' => 'zhtw/about',
            'faq' => 'about',


            'home-2' => '/',
            'home-am' => 'am/',
            'home-ar_jo' => 'ar_jo/',
            'home-ar' => 'ar/',
            'home-asl' => 'asl/',
            'home-bho' => 'bho/',
            'home-bn' => 'bn/',
            'home-bs' => 'bs/',
            'home-de' => 'de/',
            'home-es' => 'es/',
            'home-fa' => 'fa/',
            'home-ha' => 'ha/',
            'home-hi' => 'hi/',
            'home-hr' => 'hr/',
            'home-in' => 'in/',
            'home-it' => 'it/',
            'home-ja' => 'ja/',
            'home-kn' => 'kn/',
            'home-ko' => 'ko/',
            'home-ku' => 'ku/',
            'home-lo' => 'lo/',
            'home-mai' => 'mai/',
            'home-ml' => 'ml/',
            'home-mr' => 'mr/',
            'home-ne' => 'ne/',
            'home-or' => 'or/',
            'home-pa' => 'pa/',
            'home-pt' => 'pt/',
            'home-ro' => 'ro/',
            'home-ru' => 'ru/',
            'home-sl' => 'sl/',
            'home-so' => 'so/',
            'home-sw' => 'sw/',
            'home-ta' => 'ta/',
            'home-te' => 'te/',
            'home-th' => 'th/',
            'home-tr' => 'tr/',
            'home-ur' => 'ur/',
            'home-vi' => 'vi/',
            'home-yo' => 'yo/',
            'home-zhcn' => 'zhcn/',
            'home-zhhk' => 'zhhk/',
            'home-zhtw' => 'zhtw/',

            'login-am' => 'am/login',
            'login-ar_jo' => 'ar_jo/login',
            'login-ar' => 'ar/login',
            'login-asl' => 'asl/login',
            'login-bho' => 'bho/login',
            'login-bn' => 'bn/login',
            'login-bs' => 'bs/login',
            'login-de' => 'de/login',
            'login-es' => 'es/login',
            'login-fa' => 'fa/login',
            'login-fr' => 'fr/login',
            'login-gu' => 'gu/login',
            'login-ha' => 'ha/login',
            'login-hi' => 'hi/login',
            'login-hr' => 'hr/login',
            'login-in' => 'in/login',
            'login-it' => 'it/login',
            'login-ja' => 'ja/login',
            'login-kn' => 'kn/login',
            'login-ko' => 'ko/login',
            'login-ku' => 'ku/login',
            'login-lo' => 'lo/login',
            'login-mai' => 'mai/login',
            'login-ml' => 'ml/login',
            'login-mr' => 'mr/login',
            'login-or' => 'or/login',
            'login-pa' => 'pa/login',
            'login-pt' => 'pt/login',
            'login-ro' => 'ro/login',
            'login-ru' => 'ru/login',
            'login-sl' => 'sl/login',
            'login-so' => 'so/login',
            'login-sw' => 'sw/login',
            'login-ta' => 'ta/login',
            'login-te' => 'te/login',
            'login-th' => 'th/login',
            'login-tr' => 'tr/login',
            'login-ur' => 'ur/login',
            'login-vi' => 'vi/login',
            'login-yo' => 'yo/login',
            'login-zhcn' => 'zhcn/login',
            'login-zhhk' => 'zhhk/login',
            'login-zhtw' => 'zhtw/login',

            'privacy-policy-am' => 'am/privacy',
            'am/privacy-policy' => '/am/privacy',
            'privacy-policy-ar_jo' => 'ar_jo/privacy',
            'privacy-policy-ar' => 'ar/privacy',
            'privacy-policy-asl' => 'asl/privacy',
            'privacy-policy-bho' => 'bho/privacy',
            'privacy-policy-bn' => 'bn/privacy',
            'privacy-policy-bs' => 'bs/privacy',
            'privacy-policy-de' => 'de/privacy',
            'privacy-policy-es' => 'es/privacy',
            'privacy-policy-fa' => 'fa/privacy',
            'privacy-policy-fr' => 'fr/privacy',
            'privacy-policy-gu' => 'gu/privacy',
            'privacy-policy-ha' => 'ha/privacy',
            'privacy-policy-hi' => 'hi/privacy',
            'privacy-policy-hr' => 'hr/privacy',
            'privacy-policy-in' => 'in/privacy',
            'privacy-policy-it' => 'it/privacy',
            'privacy-policy-ja' => 'ja/privacy',
            'privacy-policy-kn' => 'kn/privacy',
            'privacy-policy-ko' => 'ko/privacy',
            'privacy-policy-ku' => 'ku/privacy',
            'privacy-policy-lo' => 'lo/privacy',
            'privacy-policy-mai' => 'mai/privacy',
            'privacy-policy-ml' => 'ml/privacy',
            'privacy-policy-mr' => 'mr/privacy',
            'privacy-policy-or' => 'or/privacy',
            'privacy-policy-pa' => 'pa/privacy',
            'privacy-policy-pt' => 'pt/privacy',
            'privacy-policy-ro' => 'ro/privacy',
            'privacy-policy-ru' => 'ru/privacy',
            'privacy-policy-sl' => 'sl/privacy',
            'privacy-policy-so' => 'so/privacy',
            'privacy-policy-sw' => 'sw/privacy',
            'privacy-policy-ta' => 'ta/privacy',
            'privacy-policy-te' => 'te/privacy',
            'privacy-policy-th' => 'th/privacy',
            'privacy-policy-tr' => 'tr/privacy',
            'privacy-policy-ur' => 'ur/privacy',
            'privacy-policy-vi' => 'vi/privacy',
            'privacy-policy-yo' => 'yo/privacy',
            'privacy-policy-zhcn' => 'zhcn/privacy',
            'privacy-policy-zhhk' => 'zhhk/privacy',
            'privacy-policy-zhtw' => 'zhtw/privacy',
            'privacy-policy' => '/privacy',


            'overview-am' => 'am/training',
            'overview-ar' => 'ar/training',
            'overview-bn' => 'bn/training',
            'overview-es' => 'es/training',
            'overview-fa' => 'fa/training',
            'overview-fr' => 'fr/training',
            'overview-hi' => 'hi/training',
            'overview-in' => 'in/training',
            'overview-it' => 'it/training',
            'overview-ku' => 'ku/training',
            'overview-mr' => 'mr/training',
            'overview-or' => 'or/training',
            'overview-so' => 'so/training',
            'overview-sw' => 'sw/training',
            'overview-ta' => 'ta/training',
            'overview-te' => 'te/training',
            'overview-th' => 'th/training',
            'overview-zhcn' => 'zhcn/training',
            'overview-zhtw' => 'zhtw/training',
            'overview' => 'training',


            'profile-am' => 'am/dashboard',
            'profile-ar_jo' => 'ar_jo/dashboard',
            'profile-ar' => 'ar/dashboard',
            'profile-asl' => 'asl/dashboard',
            'profile-bho' => 'bho/dashboard',
            'profile-bn' => 'bn/dashboard',
            'profile-bs' => 'bs/dashboard',
            'profile-de' => 'de/dashboard',
            'profile-es' => 'es/dashboard',
            'profile-fa' => 'fa/dashboard',
            'profile-fr' => 'fr/dashboard',
            'profile-gu' => 'gu/dashboard',
            'profile-ha' => 'ha/dashboard',
            'profile-hi' => 'hi/dashboard',
            'profile-hr' => 'hr/dashboard',
            'profile-in' => 'in/dashboard',
            'profile-it' => 'it/dashboard',
            'profile-ja' => 'ja/dashboard',
            'profile-kn' => 'kn/dashboard',
            'profile-ko' => 'ko/dashboard',
            'profile-ku' => 'ku/dashboard',
            'profile-lo' => 'lo/dashboard',
            'profile-mai' => 'mai/dashboard',
            'profile-ml' => 'ml/dashboard',
            'profile-mr' => 'mr/dashboard',
            'profile-ne' => 'ne/dashboard',
            'profile-or' => 'or/dashboard',
            'profile-pa' => 'pa/dashboard',
            'profile-pt' => 'pt/dashboard',
            'profile-ro' => 'ro/dashboard',
            'profile-ru' => 'ru/dashboard',
            'profile-sl' => 'sl/dashboard',
            'profile-so' => 'so/dashboard',
            'profile-sw' => 'sw/dashboard',
            'profile-ta' => 'ta/dashboard',
            'profile-te' => 'te/dashboard',
            'profile-th' => 'th/dashboard',
            'profile-tr' => 'tr/dashboard',
            'profile-ur' => 'ur/dashboard',
            'profile-vi' => 'vi/dashboard',
            'profile-yo' => 'yo/dashboard',
            'profile-zhcn' => 'zhcn/dashboard',
            'profile-zhhk' => 'zhhk/dashboard',
            'profile-zhtw' => 'zhtw/dashboard',

            'progress-ar' => 'ar/training',
            'progress-bn' => 'bn/training',
            'progress-es' => 'es/training',
            'progress-fa' => 'fa/training',
            'progress-fr' => 'fr/training',
            'progress-hi' => 'hi/training',
            'progress-in' => 'in/training',
            'progress-it' => 'it/training',
            'progress-mr' => 'mr/training',
            'progress-or' => 'or/training',
            'progress-so' => 'so/training',
            'progress-sw' => 'sw/training',
            'progress-ta' => 'ta/training',
            'progress-te' => 'te/training',
            'progress-th' => 'th/training',

            'three-month-plan-am' => 'am/dashboard',
            'three-month-plan-ar_jo' => 'ar_jo/dashboard',
            'three-month-plan-ar' => 'ar/dashboard',
            'three-month-plan-asl' => 'asl/dashboard',
            'three-month-plan-bho' => 'bho/dashboard',
            'three-month-plan-bn' => 'bn/dashboard',
            'three-month-plan-bs' => 'bs/dashboard',
            'three-month-plan-de' => 'de/dashboard',
            'three-month-plan-es' => 'es/dashboard',
            'three-month-plan-fa' => 'fa/dashboard',
            'three-month-plan-fr' => 'fr/dashboard',
            'three-month-plan-gu' => 'gu/dashboard',
            'three-month-plan-ha' => 'ha/dashboard',
            'three-month-plan-hi' => 'hi/dashboard',
            'three-month-plan-hr' => 'hr/dashboard',
            'three-month-plan-in' => 'in/dashboard',
            'three-month-plan-it' => 'it/dashboard',
            'three-month-plan-ja' => 'ja/dashboard',
            'three-month-plan-kn' => 'kn/dashboard',
            'three-month-plan-ko' => 'ko/dashboard',
            'three-month-plan-ku' => 'ku/dashboard',
            'three-month-plan-lo' => 'lo/dashboard',
            'three-month-plan-mai' => 'mai/dashboard',
            'three-month-plan-ml' => 'ml/dashboard',
            'three-month-plan-mr' => 'mr/dashboard',
            'three-months-plan-ne' => 'ne/dashboard',
            'three-month-plan-or' => 'or/dashboard',
            'three-month-plan-pa' => 'pa/dashboard',
            'three-month-plan-pt' => 'pt/dashboard',
            'three-month-plan-ro' => 'ro/dashboard',
            'three-month-plan-ru' => 'ru/dashboard',
            'three-month-plan-sl' => 'sl/dashboard',
            'three-month-plan-so' => 'so/dashboard',
            'three-month-plan-sw' => 'sw/dashboard',
            'three-month-plan-ta' => 'ta/dashboard',
            'three-month-plan-te' => 'te/dashboard',
            'three-month-plan-th' => 'th/dashboard',
            'three-month-plan-tr' => 'tr/dashboard',
            'three-month-plan-ur' => 'ur/dashboard',
            'three-month-plan-vi' => 'vi/dashboard',
            'three-month-plan-yo' => 'yo/dashboard',
            'three-month-plan-zhcn' => 'zhcn/dashboard',
            'three-month-plan-zhhk' => 'zhhk/dashboard',
            'three-month-plan-zhtw' => 'zhtw/dashboard',
            'three-month-plan' => '/dashboard',

            'resource-ja' => 'ja/resource',
            'resource-ta' => 'ta/resource',
            'resources-am' => 'am/resource',
            'resources-ar_jo' => 'ar_jo/resource',
            'resources-ar' => 'ar/resource',
            'resources-asl' => 'asl/resource',
            'resources-bho' => 'bho/resource',
            'resources-bn' => 'bn/resource',
            'resources-bs' => 'bs/resource',
            'resources-de' => 'de/resource',
            'resources-es' => 'es/resource',
            'resources-fa' => 'fa/resource',
            'resources-fr' => 'fr/resource',
            'resources-gu' => 'gu/resource',
            'resources-ha' => 'ha/resource',
            'resources-hi' => 'hi/resource',
            'resources-hr' => 'hr/resource',
            'resources-in' => 'in/resource',
            'resources-it' => 'it/resource',
            'resources-kn' => 'kn/resource',
            'resources-ko' => 'ko/resource',
            'resources-ku' => 'ku/resource',
            'resources-lo' => 'lo/resource',
            'resources-mai' => 'mai/resource',
            'resources-ml' => 'ml/resource',
            'resources-mr' => 'mr/resource',
            'resources-or' => 'or/resource',
            'resources-pa' => 'pa/resource',
            'resources-pt' => 'pt/resource',
            'resources-ro' => 'ro/resource',
            'resources-ru' => 'ru/resource',
            'resources-sl' => 'sl/resource',
            'resources-so' => 'so/resource',
            'resources-sw' => 'sw/resource',
            'resources-te' => 'te/resource',
            'resources-th' => 'th/resource',
            'resources-tr' => 'tr/resource',
            'resources-ur' => 'ur/resource',
            'resources-vi' => 'vi/resource',
            'resources-yo' => 'yo/resource',
            'resources-zhcn' => 'zhcn/resource',
            'resources-zhhk' => 'zhhk/resource',
            'resources-zhtw' => 'zhtw/resource',


            'training-am' => 'am/training',
            'training-ar_jo' => 'ar_jo/training',
            'training-ar' => 'ar/training',
            'training-asl' => 'asl/training',
            'training-bho' => 'bho/training',
            'training-bn' => 'bn/training',
            'training-bs' => 'bs/training',
            'training-cycle-for-maturing-disciples-am' => '',
            'training-de' => 'de/training',
            'training-es' => 'es/training',
            'training-fa' => 'fa/training',
            'training-fr' => 'fr/training',
            'training-gu' => 'gu/training',
            'training-ha' => 'ha/training',
            'training-hi' => 'hi/training',
            'training-hr' => 'hr/training',
            'training-id' => 'id/training',
            'training-it' => 'it/training',
            'training-ja' => 'ja/training',
            'training-kn' => 'kn/training',
            'training-ko' => 'ko/training',
            'training-ku' => 'ku/training',
            'training-lo' => 'lo/training',
            'training-mai' => 'mai/training',
            'training-ml' => 'ml/training',
            'training-mr' => 'mr/training',
            'training-ne' => 'ne/training',
            'training-or' => 'or/training',
            'training-pa' => 'pa/training',
            'training-pt' => 'pt/training',
            'training-ro' => 'ro/training',
            'training-ru' => 'ru/training',
            'training-sl' => 'sl/training',
            'training-so' => 'so/training',
            'training-swa' => 'swa/training',
            'training-ta' => 'ta/training',
            'training-te' => 'te/training',
            'training-th' => 'th/training',
            'training-tr' => 'tr/training',
            'training-ur' => 'ur/training',
            'training-vi' => 'vi/training',
            'training-yo' => 'yo/training',
            'training-zhcn' => 'zhcn/training',
            'training-zhhk' => 'zhhk/training',
            'training-zhtw' => 'zhtw/training',


            'translation-bho' => 'bho/translation',
            'translation-kn' => 'kn/translation',
            'translation-progress-am' => 'am/translation-progress',
            'translation-progress-asl' => 'asl/translation-progress',
            'translation-progress-ha' => 'ha/translation-progress',
            'translation-progress-hr' => 'hr/translation-progress',
            'translation-progress-ja' => 'ja/translation-progress',
            'translation-progress-ku' => 'ku/translation-progress',
            'translation-progress-mai' => 'mai/translation-progress',
            'translation-progress-ro' => 'ro/translation-progress',
            'translation-progress-sl' => 'sl/translation-progress',
            'translation-progress-tr' => 'tr/translation-progress',


        ];
        return $pages;


        // return [
        //     'fr/course-fr' => $z . 'fr/training-fr',
        //     'login-ml//?action=lostpassword' => $z . 'ml/login?action=lostpassword',
        //     'login-ml/?action=lostpassword' => $z . 'ml/login?action=lostpassword',
        //     'asl/leadership-in-networks-2' => $z . 'asl/leadership-in-networks-asl',
        //     'fr/home-2' => $l . 'fr',
        //     'ar_jo/login-ar_jo/' => $z . 'ar_jo/login',
        //     'ar/the-lords-supper-and-how-to-lead-it-ar' => '',
        //     'fr/course-fr' => '',
        //     'login-ml/?action=lostpassword' => '',
        //     'asl/leadership-in-networks-2' => '',
        //     'fr/home-2' => '',
        //     'ar_jo/login-ar_jo' => '',
        //     'ar-tn/resources-ar-tn' => '',
        //     'ku/overview-ku' => '',
        //     'lo/course-lo' => '',
        //     'id/login-in' => '',
        //     'bho/course-bho' => '',
        //     'tr/course-tr' => '',
        //     'ml/course-ml' => '',
        //     'id/four-fields-id' => '',
        //     'coaching/zume_app/last100_hours' => '',
        //     'hi/login-hi' => '',
        //     'es/new-life-church-es' => '',
        //     'ar-tn/accountability-groups-ar-tn' => '',
        //     'ja' => '',
        //     'ta/a-person-of-peace-and-how-to-find-one-ta' => '',
        //     'bho/home-bho' => '',
        //     'am/baptism-and-how-to-do-it-am' => '',
        //     'gu/the-kingdom-economy-gu' => '',
        //     'am/how-to-spend-an-hour-in-prayer-am' => '',
        //     'home' => '',
        //     'ru/login-ru/?action=lostpassword' => '',
        //     'de/3-3-group-meeting-pattern-de' => '',
        //     'cookie-policy' => '',
        //     'pa/a-person-of-peace-and-how-to-find-one-pa' => '',
        //     'ml/home-ml' => '',
        //     'ar-tn/privacy-policy-ar-tn' => '',
        //     'pulse' => '',
        //     'ar-tn/spiritual-breathing-is-hearing-and-obeying-god-ar-tn' => '',
        //     'th/progress-th' => '',
        //     'ar-tn/definition-of-disciple-and-church-ar-tn' => '',
        //     'ml/3-3-group-meeting-pattern-ml' => '',
        //     'es/welcome-to-gods-family-es' => '',
        //     'fr/welcome-to-gods-family-fr' => '',
        //     'livetenotwo' => '',
        //     'ja' => '',
        //     'kn/login-kn' => '',
        //     'am/spiritual-breathing-is-hearing-and-obeying-god-am' => '',
        //     'kn/translation-kn' => '',
        //     'ar-tn/generational-mapping-ar-tn' => '',
        //     'ar-tn/prayer-walking-and-how-to-do-it-ar-tn' => '',
        //     'am/duckling-discipleship-leading-immediately-am' => '',
        //     'swa/login-sw' => '',
        //     'ar-tn/consumer-vs-producer-lifestyle-ar-tn' => '',
        //     'ar-tn/the-kingdom-economy-ar-tn' => '',
        //     'ar-tn/baptism-and-how-to-do-it-ar-tn' => '',
        //     'join-the-community' => '',
        //     'ar-tn/expect-non-sequential-growth-ar-tn' => '',
        //     'how-to-spend-an-' => '',
        //     'the-lords-supper-and-how-to-lead-it-id' => '',
        //     'ar-tn/generational-mapping-ar-tn' => '',
        //     'ta/course-ta' => '',
        //     'kn/course-kn' => '',
        //     'asl/login-asl' => '',
        //     'ml/a-person-of-peace-and-how-to-find-one-ml' => '',
        //     'ur/ur-3_3-group-meeting-pattern' => '',
        //     'bho/translation-bho' => '',
        //     'it/progress-it' => '',
        //     'ar-tn/how-to-spend-and-hour-in-prayer-ar-tn' => '',
        //     'ta/home-ta' => '',
        //     'ar-tn/translation-progress-ar-tn' => '',
        //     'ar-tn/leadership-cells-ar-tn' => '',
        //     'ko/course-ko' => '',
        //     'stats' => '',
        //     'ar-tn/accountability-groups-ar-tn' => '',
        //     'ar-tn/spiritual-breathing-is-hearing-and-obeying-god-ar-tn' => '',
        //     'fr/how-to-follow-jesus-hi' => '',
        //     'pa/login-pa' => '',
        //     'zhhk/login-zhhk' => '',
        //     'it/login-it' => '',
        //     'am/generational-mapping-am' => '',
        //     'am/duckling-discipleship-leading-immediately-am' => '',
        //     'ne/home-ne' => '',
        //     'te/login-te/?action=register' => '',
        //     'join-an-online-group' => '',
        //     'ar-tn/the-gospel-and-how-to-share-it-ar-tn' => '',
        //     'zhhk/relational-stewardship-list-of-100-zhhk' => '',
        //     'ar-tn/pace-of-multiplication-matters-ar-tn' => '',
        //     'am/privacy-policy-am' => '',
        //     'the-lords-supper-and-how-to-lead-it-ml' => '',
        //     'coaching/webform/ml/9ba50ca462807be6032832cd71efc83b' => '',
        //     'sl/home-sl' => '',
        //     'so/progress-so' => '',
        //     'mai/login-mai' => '',
        //     'ar-tn/leadership-cells-ar-tn' => '',
        //     'es/progress-es' => '',
        //     'zhcn/course-zhcn' => '',
        //     'ar-tn/eyes-to-see-where-the-kingdom-isnt-ar-tn' => '',
        //     'gu/the-lord_s-supper-and-how-to-lead-it-gu' => '',
        //     'ar-tn/faithfulness-is-better-than-knowledge-ar-tn' => '',
        //     'ar-tn/leadership-in-networks-ar-tn' => '',
        //     'bs/course-bs' => '',
        //     'ar-tn/about-ar-tn' => '',
        //     'asl/leadership-in-networks-2' => '',
        //     'ar-tn/training-cycle-for-maturing-disciples-ar-tn' => '',
        //     'es/training-cycle-for-maturing-disciples-es-2' => '',
        //     'ar-tn/cookie-policy-ar-tn' => '',
        //     'hi/home-hi' => '',
        //     'ar-tn/peer-mentoring-groups-ar-tn' => '',
        //     'ar-tn' => '',
        //     'am' => '',
        //     'ar-tn/duckling-discipleship-leading-immediately-ar-tn' => '',
        //     'ar-tn/vision-casting-the-greatest-blessing-ar-tn' => '',
        //     'gu/course-gu' => '',
        //     'welcome-to-gods-family' => '',
        //     'spiritual-' => '',
        //     'am/leadership-cells-am' => '',
        //     'ar-tn/definition-of-disciple-and-church-ar-tn' => '',
        //     'ar_jo/course-ar_jo' => '',
        //     'ar-tn/the-lords-supper-and-how-to-lead-it-ar-tn' => '',
        //     'ar/the-bless-prayer-pattern-ar' => '',
        //     'ar-tn/the-bless-prayer-pattern-ar-tn' => '',
        //     'id/the-lords-supper-and-how-to-lead-it-id' => '',
        //     'ar_jo/course-ar_jo' => '',
        //     'ne/book-ne' => '',
        //     'zhhk/course-zhhk' => '',
        //     'vi/login-vi' => '',
        //     'fr/login-fr' => '',
        //     'swa/home-sw' => '',
        //     'zhtw/login-zhtw' => '',
        //     'hi/overview-hi' => '',
        //     'pl/course-pl' => '',
        //     'tr/home-tr' => '',
        //     'mai/course-mai' => '',
        //     'hr/home-hr' => '',
        //     'swa/progress-sw' => '',
        //     'hi/the-lords-supper-and-how-to-lead-it-hi' => '',
        //     'ur/home-ur' => '',
        //     'zhcn/login-zhcn' => '',
        //     'ar-tn/how-to-spend-and-hour-in-prayer-ar-tn' => '',
        //     'am/faithfulness-is-better-than-knowledge-am' => '',
        //     'ar-tn/mobile-app-ar-tn' => '',
        //     'or/overview-or' => '',
        //     'ar-tn/training-ar-tn' => '',
        //     'ar-tn/relational-stewardship-list-of-100-ar-tn' => '',
        //     'gu/login-gu' => '',
        //     'zhhk/home-zhhk' => '',
        //     'coaching/webform/ml/20043656e8af9e665ad97527409307e1' => '',
        //     'asl/login-asl?action=register' => '',
        //     'ar/relational-stewardship-list-of-100-ar' => '',
        //     'hr/login-hr' => '',
        //     'de/course-de' => '',
        //     'th/overview-th' => '',
        //     'pl/home-pl' => '',
        //     'te/course-te' => '',
        //     'translation-progress' => '',
        //     'te/home-te' => '',
        //     'es/livetenotwo-es' => '',
        //     '(hi/faq-hi' => '',
        //     'id/faq-in' => '',
        //     'id/faq-in' => '',
        //     'ar-tn/peer-mentoring-groups-ar-tn' => '',
        //     'am/peer-mentoring-groups-am' => '',
        //     'ha/course-ha' => '',
        //     'bs/course-bs' => '',
        //     'ne/resources-ne' => '',
        //     'zhhk/vision-casting-the-greatest-blessing-zhhk' => '',
        //     'th/login-th' => '',
        //     'hr/peer-mentoring-groups-hr' => '',
        //     'id/progress-in' => '',
        //     'am/coaching-checklist-am' => '',
        //     'ro/login-ro' => '',
        //     'ar/about-ar' => '',
        //     'ar/about-ar' => '',
        //     'am/pace-of-multiplication-matters-am' => '',
        //     'ar-tn/pace-of-multiplication-matters-ar-tn' => '',
        //     'ru/pace-of-multiplication-matters-ru-2' => '',
        //     'login-sl/?action=register' => '',
        //     'ur/person-of-peace-and-how-to-find-one-ur' => '',
        //     'ar-tn/how-to-follow-jesus-ar-tn' => '',
        //     'hi/the-lords-supper-and-how-to-lead-it-hi' => '',
        //     'fa/the-lord' => '',
        //     'hi/course-hi' => '',
        //     'bn/about-bn' => '',
        //     'fa/eyes-to-see-where-the-kingdom-isn' => '',
        //     'yo/home-yo' => '',
        //     'fa/the-lord’s-supper-and-how-to-lead-it-fa' => '',
        //     'ar-tn/faq-ar-tn' => '',
        //     'bn/about-bn' => '',
        //     'am/translation-progress-am' => '',
        //     'pl/resources-pl' => '',
        //     'ar_jo/eyes-to-see-where-the-kingdom-isn' => '',
        //     'ar_jo/the-lord' => '',
        //     'ar_jo/the-lord’s-supper-and-how-to-lead-it-ar_jo' => '',
        //     'am/home-am' => '',
        //     'tr/eyes-to-see-where-the-kingdom-isn' => '',
        //     'mr/progress-mr' => '',
        //     'hi/login-hi/?action=register' => '',
        //     'tr/the-lord' => '',
        //     'tr/3/3-group-meeting-pattern-tr' => '',
        //     'tr/the-lord’s-supper-and-how-to-lead-it-tr' => '',
        //     'ar-tn/login-ar-tn' => '',
        //     'zhtw/course-zhtw' => '',
        //     'kn/3-3-group-meeting-pattern-kn' => '',
        //     'am/the-kingdom-economy-am' => '',
        //     'am/cookie-policy-am' => '',
        //     'login-th/?action=lostpassword' => '',
        //     'login-th//?action=register' => '',
        //     'login-th/?action=register' => '',
        //     'th/login-th/?action=register' => '',
        //     'three-month-plan-th' => '',
        //     'th/three-month-plan-th' => '',
        //     'th/profile-th' => '',
        //     'hr/course-hr' => '',
        //     'th/login-th' => '',
        //     'th/login-th' => '',
        //     'ar/login-ar' => '',
        //     'zhcn/course-zhcn' => '',
        //     'fa/home-fa' => '',
        //     'login-th' => '',
        //     'login-th' => '',
        //     'login-th' => '',
        //     'pl/training-pl' => '',
        //     'am/training-am' => '',
        //     'am/vision-am' => '',
        //     'bn/login-bn' => '',
        //     'ne/the-lord' => '',
        //     'ne/3/3-group-meeting-pattern-ne' => '',
        //     'ne/eyes-to-see-where-the-kingdom-isn' => '',
        //     'ne/the-lord’s-supper-and-how-to-lead-it-ne' => '',
        //     'ar/overview-ar' => '',
        //     'id/four-fields-id' => '',
        //     'am/vision-casting-the-greatest-blessing-am' => '',
        //     'am/leadership-in-networks-am' => '',
        //     'id/progress-in' => '',
        //     'id/progress-in' => '',
        //     'sl/relational-stewardship-list-of-100-sl' => '',
        //     'definition-of-disciple-and-church/?gclid=Cj0KCQjwnNyUBhCZARIsAI9AYlFk1wtbeeoYfY-Z14IX88VPWWNoM1zlcwAA8keajKFZwHNMb9sI2ZAaAr7EEALw_wcB' => '',
        //     'definition-of-disciple-and-church//1000' => '',
        //     'definition-of-disciple-and-church/?gclid=CjwKCAjwjbCDBhAwEiwAiudBy19j_Jv535mIfmD3e1QcbCm7tHT5ELKG--_st86fSobmO-e1Yp_ybRoCRQsQAvD_BwE' => '',
        //     'ro/login-ro/?action=register' => '',
        //     'login-ro/?action=lostpassword' => '',
        //     'ro/login-ro' => '',
        //     'login-ro' => '',
        //     'login-ro' => '',
        //     'es/three-month-plan-es' => '',
        //     'ar-tn/relational-stewardship-list-of-100-ar-tn' => '',
        //     'dashboard-es' => '',
        //     'ru/course-ru' => '',
        //     'es/login-es' => '',
        //     'am/always-part-of-two-churches-am' => '',
        //     'ar-tn/always-part-of-two-churches-ar-tn' => '',
        //     'so/course-so' => '',
        //     'vi/home-vi' => '',
        //     'hi/course-hi' => '',
        //     'ar/3-3-group-meeting-pattern-ar' => '',
        //     'ar/home-ar' => '',
        //     'am/accountability-groups-am' => '',
        //     'ne/about-ne' => '',
        //     'sl/login-sl' => '',
        //     'am/relational-stewardship-list-of-100-am' => '',
        //     'ar/progress-ar' => '',
        //     'ar-tn/translation-progress-ar-tn' => '',
        //     'am/about-am' => '',
        //     'th/home-th' => '',
        //     'id/overview-in' => '',
        //     'id/the-lords-supper-and-how-to-lead-it-id' => '',
        //     'am/resources-am' => '',
        //     'fa/progress-fa' => '',
        //     'am/training-cycle-for-maturing-disciples-am' => '',
        //     'ar-tn/vision-ar-tn' => '',
        //     'wp-json/zume/v4/piece' => '',
        //     'god-uses-ordinary-people//1000' => '',
        //     'id/course-id' => '',
        //     'god-uses-ordinary-people/?gclid=EAIaIQobChMI4cCk5J_E7QIVAdvACh1Vd' => '',
        //     'th/course-th' => '',
        //     'bn/login-bn/?action=register' => '',
        //     'login-bn/?action=register' => '',
        //     'ar-tn/prayer-walking-and-how-to-do-it-ar-tn' => '',
        //     'login-bn/?action=lostpassword' => '',
        //     'bn/login-bn/?action=lostpassword' => '',
        //     'three-month-plan-bn' => '',
        //     'bn/three-month-plan-bn' => '',
        //     'pl/about-pl' => '',
        //     'vi/the-lord’s-supper-and-how-to-lead-it-vi' => '',
        //     'vi/the-lord' => '',
        //     'vi/3/3-group-meeting-pattern-vi' => '',
        //     'vi/eyes-to-see-where-the-kingdom-isn' => '',
        //     'hi/resources-hi' => '',
        //     'gu/person-of-peace-and-how-to-find-one-gu' => '',
        //     'bn/login-bn' => '',
        //     'es/home-es' => '',
        //     'am/expect-non-sequential-growth-am' => '',
        //     'login-bn' => '',
        //     'zhcn/progress-zhcn' => '',
        //     'login-bn' => '',
        //     'the-kingdom-economy-am' => '',
        //     'bn/login-bn' => '',
        //     'bn/login-bn' => '',
        //     'login-bn' => '',
        //     'login-bn' => '',
        //     'mr/progress-mr' => '',
        //     'mr/progress-mr' => '',
        //     'es/login-es' => '',
        //     'es/login-es' => '',
        //     'es/new-life-church-es' => '',
        //     'login-es' => '',
        //     'login-es' => '',
        //     'login-es' => '',
        //     'ar/overview-ar' => '',
        //     'es/login-es' => '',
        //     'sl/home-sl' => '',
        //     'ar/overview-ar' => '',
        //     'hi/resources-hi' => '',
        //     'ar-tn/the-bless-prayer-pattern-ar-tn' => '',
        //     'am/the-bless-prayer-pattern-am' => '',
        //     'ar/the-bless-prayer-pattern-ar' => '',
        //     'ar-tn' => '',
        //     'ar-tn/expect-non-sequential-growth-ar-tn' => '',
        //     'bs/login-bs' => '',
        //     'ar-tn/resources-ar-tn' => '',
        //     'ne/resources-ne' => '',
        //     'ta/resource-ta' => '',
        //     'es/overview-es' => '',
        //     'bn/overview-bn' => '',
        //     'it/progress-it' => '',
        //     'fa/overview-fa' => '',
        //     'ar/home-ar' => '',
        //     'th/home-th' => '',
        //     'th/home-th' => '',
        //     'kn/expect-non-sequential-growth-kn' => '',
        //     'ar/one-page-course-ar' => '',
        //     'ar_jo/home-ar_jo' => '',
        //     'three-month-plan-ar' => '',
        //     'three-month-plan-ar' => '',
        //     '3-3-group-meeting-pattern-ml' => '',
        //     'am/god-uses-ordinary-people-am' => '',
        //     'ar/login-ar/?action=register' => '',
        //     'ar/home-ar' => '',
        //     'ar/three-month-plan-ar' => '',
        //     'ar-tn/how-to-follow-jesus-ar-tn' => '',
        //     'am/how-to-follow-jesus-am' => '',
        //     'login-ar/?action=lostpassword' => '',
        //     'zhcn/如何跟随耶稣' => '',
        //     'duckling-discipleship-leading-sooner//1000' => '',
        //     'login-ar/?action=register' => '',
        //     'ar/login-ar' => '',
        //     'ar/login-ar' => '',
        //     'login-ar' => '',
        //     'login-ar' => '',
        //     'login-ar' => '',
        //     'login-ar' => '',
        //     'prayer-walking//1000' => '',
        //     'prayer-walking/?gclid=Cj0KCQjwvaeJBhCvARIsABgTDM41eBiUaq8x08LE3ORNnAxNPYzMmUMYhDoLWQVxQ4U86BUwn3YhJxoaAv7MEALw_wcB' => '',
        //     'a-person-of-peace-and-how-to-find-one//1000' => '',
        //     '(fa/privacy-policy-fa/)' => '',
        //     '(fa/privacy-policy-fa' => '',
        //     'pt/soaps-bible-reading-pt//1000' => '',
        //     'prayer-walking/?gclid=CjwKCAjw34n5BRA9EiwA2u9k3y5b0pZ512wjrOygSMwUeim3LxdusUOjIxu7iSIGSlc5ZRy6g9f1bRoChCQQAvD_BwE&utm_campaign=later-linkinbio-serve_asia_us&utm_content=later-9057416&utm_medium=social&utm_source=instagram' => '',
        //     'kn/a-person-of-peace-and-how-to-find-one-kn' => '',
        //     'am/a-person-of-peace-and-how-to-find-one-am' => '',
        //     'ne/course-ne' => '',
        //     'ko/login-ko' => '',
        //     'mai/translation-progress-mai' => '',
        //     'soaps-bible-reading//1000' => '',
        //     'ar-tn/leadership-in-networks-ar-tn' => '',
        //     'bn/course-bn' => '',
        //     'ha/translation-progress-ha' => '',
        //     'login-es//?action=register' => '',
        //     '3-3-group-meeting-pattern//1000' => '',
        //     'course' => '',
        //     'ta/login-ta' => '',
        //     'mai/home-mai' => '',
        //     'ar-tn/welcome-to-gods-family-ar-tn' => '',
        //     'generational-mapping//1000' => '',
        //     'faithfulness-is-better-than-knowledge//1000' => '',
        //     'de/3-3-group-meeting-pattern-de' => '',
        //     'the-bless-prayer-pattern//1000' => '',
        //     'spiritual-breathing-is-hearing-and-obeying-god//1000' => '',
        //     'ar-tn/always-part-of-two-churches-ar-tn' => '',
        //     '(ar/progress-ar/)' => '',
        //     '(ar/progress-ar' => '',
        //     '(progress/)' => '',
        //     '(progress)' => '',
        //     '(progress' => '',
        //     'progress' => '',
        //     'ne/join-an-online-group-ne' => '',
        //     'terms-of-service' => '',
        //     'sl/login-sl/?action=lostpassword' => '',
        //     'login-sl//?action=lostpassword' => '',
        //     'sl/login-sl/?action=register' => '',
        //     'prepare-your-3-minute-testimony/?gclid=EAIaIQobChMIhO3gofDy6QIVAb7ACh3cCwrbEAAYASAAEgKprPD_BwE' => '',
        //     'duckling-discipleship-leading-sooner/?gclid=CjwKCAjwjbCDBhAwEiwAiudBy3BjnI4jwkxvZ8ZKsuSUspD7CMwwgTp8ofEWAaGuGpJL6dssipwpZRoCWlUQAvD_BwE' => '',
        //     'login-sl//?action=register' => '',
        //     'prepare-your-3-minute-testimony//1000' => '',
        //     'baptism-and-how-to-do-it//1000' => '',
        //     'hi/progress-hi' => '',
        //     'bs/login-bs/?action=lostpassword' => '',
        //     'bs/login-bs/?action=register' => '',
        //     'login-bs/?action=lostpassword' => '',
        //     'am/3-3-group-meeting-pattern-am' => '',
        //     'book' => '',
        //     'how-to-spend-an-hour-in-prayer//1000' => '',
        //     'login-bs/?action=register' => '',
        //     'three-month-plan-bs' => '',
        //     'bs/three-month-plan-bs' => '',
        //     'bs/login-bs' => '',
        //     '(fa/progress-fa' => '',
        //     'the-lords-supper-and-how-to-lead-it//1000' => '',
        //     'the-kingdom-economy//1000' => '',
        //     'the-lords-supper-and-how-to-lead-it/?gclid=EAIaIQobChMIzZ3MztPZ6AIVUL7ACh250QKfEAAYASAAEgKIfPD_BwE' => '',
        //     'ar-tn/3-3-group-meeting-pattern-ar-tn' => '',
        //     '(id/overview-in/)' => '',
        //     '(id/overview-in' => '',
        //     'login-sl/?action=lostpassword' => '',
        //     'sl/three-month-plan-sl' => '',
        //     'sl/login-sl' => '',
        //     'login-sl' => '',
        //     'the-lords-supper-and-how-to-lead-it-id' => '',
        //     'verification' => '',
        //     'login-bs' => '',
        //     'login-bs' => '',
        //     '3-3-group-meeting-pattern-ar' => '',
        //     'login-sl' => '',
        //     '4-aspects-of-starting-a-multiplying-community' => '',
        //     'ro/home-ro' => '',
        //     'join-an-online-group' => '',
        //     'life-church' => '',
        //     'translation-progress' => '',
        //     'course-id' => '',
        //     'ar-tn/a-person-of-peace-and-how-to-find-one-ar-tn' => '',
        //     'zhtw/progress-zhtw' => '',
        //     'es/pulse-es' => '',
        //     'hr/home-hr' => '',
        //     'stats' => '',
        //     'language-progress' => '',
        //     'new-life-church' => '',
        //     'ar/welcome-to-gods-family-ar' => '',
        //     'it/home-it' => '',
        //     'zhcn/overview-zhcn' => '',
        //     'mr/login-mr' => '',
        //     'home' => '',
        //     'zhtw/home-zhtw' => '',
        //     'join-the-community' => '',
        //     '(th/course-th/)' => '',
        //     'es/progress-es' => '',
        //     'overview' => '',
        //     '(th/course-th' => '',
        //     'hr/translation-progress-hr' => '',
        //     'it/cookie-policy-it' => '',
        //     'es/como-seguir-a-jesus' => '',
        //     'ne/book-ne' => '',
        //     'hr/cookie-policy-hr' => '',
        //     'swa/course-sw' => '',
        //     'es/livetenotwo-es' => '',
        //     'ne/terms-of-service-ne' => '',
        //     'de/course-de' => '',
        //     'de/home-de' => '',
        //     'vi/course-vi' => '',
        //     'ar-tn/prepare-your-3-minute-testimony-ar-tn' => '',
        //     'hi/home-hi' => '',
        //     'ha/home-ha' => '',
        //     'ar-tn/terms-of-service-ar-tn' => '',
        //     'sl/course-sl' => '',
        //     'am' => '',
        //     'ar-tn/home-ar-tn' => '',
        //     'ar-tn/vision-ar-tn' => '',
        //     'ro/course-ro' => '',
        //     'bs/home-bs' => '',
        //     'ar-tn/3-circles-gospel-presentation-ar-tn' => '',
        //     'ne/home-ne' => '',
        //     'pulse' => '',
        //     'zhcn/home-zhcn' => '',
        //     'ne/join-the-community-ne' => '',
        //     'ha/course-ha' => '',
        //     'livetenotwo' => '',
        //     'ar-tn/cookie-policy-ar-tn' => '',
        //     'swa/progress-sw' => '',
        //     'sl/translation-progress-sl' => '',
        //     'swa/overview-sw' => '',
        //     'ja' => '',
        //     'ro/translation-progress-ro' => '',
        //     'it/course-it' => '',
        //     'zhtw/overview-zhtw' => '',
        //     'ar-tn/mobile-app-ar-tn' => '',
        //     'pt/home-pt' => '',
        //     'es/course-es' => '',
        //     'pt/course-pt' => '',
        //     'cookie-policy' => '',
        //     'course' => '',
        //     'swa/home-sw' => '',
        //     'asl/home-asl' => '',
        //     'bs/cookie-policy-bs' => '',
        //     'ar-tn/get-a-coach-ar-tn' => '',
        //     'asl/translation-progress-asl' => '',
        //     'es/ajesusleimporta' => '',
        //     'welcome-to-gods-family' => '',
        //     'vi/home-vi' => '',
        //     'es/welcome-to-gods-family-es' => '',
        //     'ha/translation-progress-ha' => '',
        //     'ar-tn/?s=%7Bsearch_term_string%7D' => '',
        //     'ar-tn' => '',
        //     'ar-tn' => '',
        //     'ar-tn' => '',
        //     'ar-tn/soaps-bible-reading-ar-tn' => '',
        //     'wp-json/zume/v1/register_via_facebook' => '',
        //     'wp-json/zume/v1/register_via_google' => '',
        //     'app' => '',
        //     'zume_app/heatmap_registrations' => '',
        //     'am/course-am' => '',
        //     'ar/course-ar' => '',
        //     'new-life-church' => '',
        //     'mr/overview-mr' => '',
        //     'login-ko//?action=lostpassword' => '',
        //     'bn/progress-bn' => '',
        //     'login-ko/?action=lostpassword' => '',
        //     'ko/login-ko/?action=lostpassword' => '',
        //     'login-ko//?action=register' => '',
        //     'three-month-plan-ta' => '',
        //     'ko/one-page-course-ko' => '',
        //     '(ta/login-ta/)' => '',
        //     'three-month-plan-ta' => '',
        //     'three-month-plan-ko' => '',
        //     'ta/login-ta/?action=register' => '',
        //     'three-month-plan-ko' => '',
        //     'ta/one-page-course-ta' => '',
        //     'ko/three-month-plan-ko' => '',
        //     'course/?group=bcb874219402380c478773d8aaa0b2bcaa5d177f1027614f5202dc5bc8365b0e06ce716c657e7f93&session=4' => '',
        //     '(course/)' => '',
        //     'ta/three-month-plan-ta' => '',
        //     'login-ta/?action=lostpassword' => '',
        //     'course/?group=2ff1cad28f92964a6e3ac9407b5f2b4f3d193938a0ec2072330c3d5c30c9b063&session=6' => '',
        //     '(course' => '',
        //     'course' => '',
        //     'login-ta/?action=register' => '',
        //     'login-ta' => '',
        //     'leadership-in-networks-ar-tn' => '',
        //     'ta/progress-ta' => '',
        //     '(bn/course-bn/)' => '',
        //     'gu/eyes-to-see-where-the-kingdom-isn_t-gu' => '',
        //     '(ta/login-ta' => '',
        //     '(bn/course-bn' => '',
        //     '(login-ta)' => '',
        //     'coaching/webform/ml/cc6b4595104d4dd5242ff81d3566c60a' => '',
        //     'login-ta' => '',
        //     'login-ta' => '',
        //     'ta/login-ta' => '',
        //     'so/login-so' => '',
        //     'ja/login-ja' => '',
        //     'ar-tn/faq-ar-tn' => '',
        //     'or/login-or' => '',
        //     'bho/login-bho' => '',
        //     'ur/login-ur' => '',
        //     'person-of-peace-and-how-to-find-one-gu' => '',
        //     'login-or//?action=lostpassword' => '',
        //     'ar-tn/soaps-bible-reading-ar-tn' => '',
        //     'ar-tn/home-ar-tn' => '',
        //     'course-lo' => '',
        //     'am/faq-am' => '',
        //     'it/course-it' => '',
        //     'lo/login-lo' => '',
        //     'ne/terms-of-service-ne' => '',
        //     'fr/progress-fr' => '',
        //     'es/app/plan-' => '',
        //     'ar-tn/training-cycle-for-maturing-disciples-ar-tn' => '',
        //     'asl/translation-progress-asl' => '',
        //     'es/pulse-es' => '',
        //     'asl/home-asl' => '',
        //     'ar/how-to-have-church-at-home' => '',
        //     'coaching/webform/ml/12fe5ae873e772e9563a3c065c087cfa' => '',
        //     'mr/course-mr' => '',
        //     'kn/home-kn' => '',
        //     'bn/home-bn' => '',
        //     'am/the-lords-supper-and-how-to-lead-it-am' => '',
        //     'ar/the-lords-supper-and-how-to-lead-it-ar' => '',
        //     '(ar/)' => '',
        //     'three-month-plan-mr' => '',
        //     'mr/login-mr/?action=register' => '',
        //     '(mr/login-mr/)' => '',
        //     'three-month-plan-mr' => '',
        //     'mr/one-page-course-mr' => '',
        //     'mr/login-mr' => '',
        //     'mr/three-month-plan-mr' => '',
        //     'ar-tn/consumer-vs-producer-lifestyle-ar-tn' => '',
        //     'login-mr/?action=lostpassword' => '',
        //     '(dashboard-mr)' => '',
        //     'login-mr/?action=register' => '',
        //     '(mr/login-mr' => '',
        //     '(login-mr/)' => '',
        //     'login-mr' => '',
        //     'login-mr' => '',
        //     'ha/login-ha' => '',
        //     'tr/login-tr/?action=lostpassword' => '',
        //     'tr/login-tr/?action=register' => '',
        //     'zhtw/歡迎來到神的大家庭' => '',
        //     'id/course-in' => '',
        //     'login-ko' => '',
        //     'login-ru//?action=lostpassword' => '',
        //     'login-ru//?action=register' => '',
        //     'three-month-plan-ru' => '',
        //     'three-month-plan-ru' => '',
        //     'ru/login-ru/?action=register' => '',
        //     'so/login-so/?action=register' => '',
        //     '(so/login-so/)' => '',
        //     'so/login-so' => '',
        //     '(so/login-so/)' => '',
        //     'three-month-plan-so' => '',
        //     'so/one-page-course-so' => '',
        //     'so/three-month-plan-so' => '',
        //     'login-so/?action=register' => '',
        //     '(so/login-so' => '',
        //     '(so/login-so)' => '',
        //     'login-so' => '',
        //     'login-so' => '',
        //     'login-so' => '',
        //     'so/login-so' => '',
        //     'am/consumer-vs-producer-lifestyle-am' => '',
        //     'three-month-plan-or' => '',
        //     'or/login-or/?action=register' => '',
        //     'or/one-page-course-or' => '',
        //     'or/three-month-plan-or' => '',
        //     'login-or/?action=lostpassword' => '',
        //     '(or/login-or/)' => '',
        //     '(ta/progress-ta/)' => '',
        //     '(ta/progress-ta' => '',
        //     'login-or/?action=register' => '',
        //     '(or/login-or' => '',
        //     '(or/login-or)' => '',
        //     '(login-or)' => '',
        //     'eyes-to-see-where-the-kingdom-isn_t-gu' => '',
        //     'login-or' => '',
        //     'ru/one-page-course-ru' => '',
        //     'login-or' => '',
        //     'ru/three-month-plan-ru' => '',
        //     'or/login-or' => '',
        //     'login-ru/?action=lostpassword' => '',
        //     'login-ru/?action=register' => '',
        //     'ko/home-ko' => '',
        //     '(dashboard-th)' => '',
        //     'three-month-plan-it' => '',
        //     'it/login-it/?action=register' => '',
        //     'tr/login-tr/?action=logout' => '',
        //     'login-tr/?action=lostpassword' => '',
        //     '(fr/progress-fr' => '',
        //     'generational-mapping-ar-tn' => '',
        //     'login-tr/?action=register' => '',
        //     'https://zume.traininglogin-ar' => '',
        //     'prayer-walking//1000' => '',
        //     'prayer-walking/?gclid=Cj0KCQjwvaeJBhCvARIsABgTDM41eBiUaq8x08LE3ORNnAxNPYzMmUMYhDoLWQVxQ4U86BUwn3YhJxoaAv7MEALw_wcB' => '',
        //     'a-person-of-peace-and-how-to-find-one//1000' => '',
        //     '(fa/privacy-policy-fa/)' => '',
        //     '(fa/privacy-policy-fa' => '',
        //     'pt/soaps-bible-reading-pt//1000' => '',
        //     'prayer-walking/?gclid=CjwKCAjw34n5BRA9EiwA2u9k3y5b0pZ512wjrOygSMwUeim3LxdusUOjIxu7iSIGSlc5ZRy6g9f1bRoChCQQAvD_BwE&utm_campaign=later-linkinbio-serve_asia_us&utm_content=later-9057416&utm_medium=social&utm_source=instagram' => '',







        ];
    }

    public function redirect( $redirect ) {
        header( 'Location: '.$redirect, true, 302 );
        exit();
    }
}
Zume_301_Redirects::instance();
