<?php
if ( !defined( 'ABSPATH' ) ) { exit; } // Exit if accessed directly.

class Zume_301_Redirects
{

    private static $_instance = null;
    public static function instance() {
        if ( is_null( self::$_instance ) ) {
            self::$_instance = new self();
        }
        return self::$_instance;
    }

    public function __construct() {
        if( dt_is_rest() ) {
            return;
        }

        if ( defined( 'DOING_CRON' ) && DOING_CRON ) {
            return;
        }

        $url = dt_get_url_path();
        if ( empty( $url ) ) {
            return;
        }

        $list = $this->list_of_urls();

        // dt_write_log('Zume_301_Redirects');
        // dt_write_log( $url );

        if ( isset( $list[$url] ) ) {
            $this->redirect( $list[$url] );
        }
    }

    public function list_of_urls() {
        $z = 'https://zume.training/';
        $l = 'https://legacy.zume.training/';

        $pages = [
            'about-am' => 'am/about',
            'about-ar_jo' => 'ar_jo/about',
            'about-ar' => 'ar/about',
            'about-asl' => 'asl/about',
            'about-bho' => 'bho/about',
            'about-bn' => 'bn/about',
            'about-bs' => 'bs/about',
            'about-de' => 'de/about',
            'about-es' => 'es/about',
            'about-es-es' => 'es/about',
            'about-fa' => 'fa/about',
            'about-fr' => 'fr/about',
            'about-gu' => 'gu/about',
            'about-ha' => 'ha/about',
            'about-hi' => 'hi/about',
            'about-hr' => 'hr/about',
            'about-in' => 'in/about',
            'about-it' => 'it/about',
            'about-ja' => 'ja/about',
            'about-kn' => 'kn/about',
            'about-ko' => 'ko/about',
            'about-ku' => 'ku/about',
            'about-lo' => 'lo/about',
            'about-mai' => 'mai/about',
            'about-ml' => 'ml/about',
            'about-mr' => 'mr/about',
            'about-or' => 'or/about',
            'about-pa' => 'pa/about',
            'about-pt' => 'pt/about',
            'about-ro' => 'ro/about',
            'about-ru' => 'ru/about',
            'about-sl' => 'sl/about',
            'about-so' => 'so/about',
            'about-sw' => 'sw/about',
            'about-ta' => 'ta/about',
            'about-te' => 'te/about',
            'about-th' => 'th/about',
            'about-tr' => 'tr/about',
            'about-ur' => 'ur/about',
            'about-vi' => 'vi/about',
            'about-yo' => 'yo/about',
            'about-zhcn' => 'zhcn/about',
            'about-zhhk' => 'zhhk/about',
            'about-zhtw' => 'zhtw/about',

            'vision-am' => 'am/training',
            'vision-ar_jo' => 'ar_jo/training',
            'vision-ar' => 'ar/training',
            'vision-asl' => 'asl/training',
            'vision-bho' => 'bho/training',
            'vision-bn' => 'bn/training',
            'vision-bs' => 'bs/training',
            'vision-de' => 'de/training',
            'vision-es' => 'es/training',
            'vision-fa' => 'fa/training',
            'vision-fr' => 'fr/training',
            'vision-gu' => 'gu/training',
            'vision-ha' => 'ha/training',
            'vision-hi' => 'hi/training',
            'vision-hr' => 'hr/training',
            'vision-id' => 'id/training',
            'vision-it' => 'it/training',
            'vision-ja' => 'ja/training',
            'vision-kn' => 'kn/training',
            'vision-ko' => 'ko/training',
            'vision-ku' => 'ku/training',
            'vision-lo' => 'lo/training',
            'vision-mai' => 'mai/training',
            'vision-ml' => 'ml/training',
            'vision-mr' => 'mr/training',
            'vision-ne' => 'ne/training',
            'vision-or' => 'or/training',
            'vision-pa' => 'pa/training',
            'vision-ro' => 'ro/training',
            'vision-ru' => 'ru/training',
            'vision-sl' => 'sl/training',
            'vision-so' => 'so/training',
            'vision-swa' => 'swa/training',
            'vision-ta' => 'ta/training',
            'vision-te' => 'te/training',
            'vision-th' => 'th/training',
            'vision-tr' => 'tr/training',
            'vision-ur' => 'ur/training',
            'vision-vi' => 'vi/training',
            'vision-yo' => 'yo/training',
            'vision-zhcn' => 'zhcn/training',
            'vision-zhhk' => 'zhhk/training',
            'vision-zhtw' => 'zhtw/training',


            'course-am' => 'am/training',
            'course-ar_jo' => 'ar_jo/training',
            'course-ar' => 'ar/training',
            'course-asl' => 'asl/training',
            'course-bho' => 'bho/training',
            'course-bn' => 'bn/training',
            'course-bs' => 'bs/training',
            'course-de' => 'de/training',
            'course-es' => 'es/training',
            'course-fa' => 'fa/training',
            'course-fr' => 'fr/training',
            'course-gu' => 'gu/training',
            'course-ha' => 'ha/training',
            'course-hi' => 'hi/training',
            'course-hr' => 'hr/training',
            'course-id' => 'id/training',
            'course-it' => 'it/training',
            'course-ja' => 'ja/training',
            'course-kn' => 'kn/training',
            'course-ko' => 'ko/training',
            'course-ku' => 'ku/training',
            'course-lo' => 'lo/training',
            'course-mai' => 'mai/training',
            'course-ml' => 'ml/training',
            'course-mr' => 'mr/training',
            'course-ne' => 'ne/training',
            'course-or' => 'or/training',
            'course-pa' => 'pa/training',
            'course-pt' => 'pt/training',
            'course-ro' => 'ro/training',
            'course-ru' => 'ru/training',
            'course-sl' => 'sl/training',
            'course-so' => 'so/training',
            'course-sw' => 'sw/training',
            'course-ta' => 'ta/training',
            'course-te' => 'te/training',
            'course-th' => 'th/training',
            'course-tr' => 'tr/training',
            'course-ur' => 'ur/training',
            'course-vi' => 'vi/training',
            'course-yo' => 'yo/training',
            'course-zhcn' => 'zhcn/training',
            'course-zhhk' => 'zhhk/training',
            'course-zhtw' => 'zhtw/training',

            'dashboard-ar' => 'ar/dashboard',
            'dashboard-bn' => 'bn/dashboard',
            'dashboard-es' => 'es/dashboard',
            'dashboard-fa' => 'fa/dashboard',
            'dashboard-fr' => 'fr/dashboard',
            'dashboard-hi' => 'hi/dashboard',
            'dashboard-in' => 'in/dashboard',
            'dashboard-it' => 'it/dashboard',
            'dashboard-ku' => 'ku/dashboard',
            'dashboard-mr' => 'mr/dashboard',
            'dashboard-or' => 'or/dashboard',
            'dashboard-so' => 'so/dashboard',
            'dashboard-sw' => 'sw/dashboard',
            'dashboard-ta' => 'ta/dashboard',
            'dashboard-te' => 'te/dashboard',
            'dashboard-th' => 'th/dashboard',
            'dashboard-zhcn' => 'zhcn/dashboard',
            'dashboard-zhtw' => 'zhtw/dashboard',


            'faq-am' => 'am/about',
            'faq-ar_jo' => 'ar_jo/about',
            'faq-ar' => 'ar/about',
            'faq-asl' => 'asl/about',
            'faq-bho' => 'bho/about',
            'faq-bn' => 'bn/about',
            'faq-bs' => 'bs/about',
            'faq-de' => 'de/about',
            'faq-es' => 'es/about',
            'faq-fa' => 'fa/about',
            'faq-fr' => 'fr/about',
            'faq-gu' => 'gu/about',
            'faq-ha' => 'ha/about',
            'faq-hi' => 'hi/about',
            'faq-hr' => 'hr/about',
            'faq-in' => 'in/about',
            'faq-it' => 'it/about',
            'faq-ja' => 'ja/about',
            'faq-kn' => 'kn/about',
            'faq-ko' => 'ko/about',
            'faq-ku' => 'ku/about',
            'faq-lo' => 'lo/about',
            'faq-mai' => 'mai/about',
            'faq-ml' => 'ml/about',
            'faq-mr' => 'mr/about',
            'faq-ne' => 'ne/about',
            'faq-or' => 'or/about',
            'faq-pa' => 'pa/about',
            'faq-pt' => 'pt/about',
            'faq-ro' => 'ro/about',
            'faq-ru' => 'ru/about',
            'faq-sl' => 'sl/about',
            'faq-so' => 'so/about',
            'faq-sw' => 'sw/about',
            'faq-ta' => 'ta/about',
            'faq-te' => 'te/about',
            'faq-th' => 'th/about',
            'faq-tr' => 'tr/about',
            'faq-ur' => 'ur/about',
            'faq-vi' => 'vi/about',
            'faq-yo' => 'yo/about',
            'faq-zhcn' => 'zhcn/about',
            'faq-zhhk' => 'zhhk/about',
            'faq-zhtw' => 'zhtw/about',
            'faq' => 'about',


            'home-2' => '/',
            'home-am' => 'am/',
            'home-ar_jo' => 'ar_jo/',
            'home-ar' => 'ar/',
            'home-asl' => 'asl/',
            'home-bho' => 'bho/',
            'home-bn' => 'bn/',
            'home-bs' => 'bs/',
            'home-de' => 'de/',
            'home-es' => 'es/',
            'home-fa' => 'fa/',
            'home-ha' => 'ha/',
            'home-hi' => 'hi/',
            'home-hr' => 'hr/',
            'home-in' => 'in/',
            'home-it' => 'it/',
            'home-ja' => 'ja/',
            'home-kn' => 'kn/',
            'home-ko' => 'ko/',
            'home-ku' => 'ku/',
            'home-lo' => 'lo/',
            'home-mai' => 'mai/',
            'home-ml' => 'ml/',
            'home-mr' => 'mr/',
            'home-ne' => 'ne/',
            'home-or' => 'or/',
            'home-pa' => 'pa/',
            'home-pt' => 'pt/',
            'home-ro' => 'ro/',
            'home-ru' => 'ru/',
            'home-sl' => 'sl/',
            'home-so' => 'so/',
            'home-sw' => 'sw/',
            'home-ta' => 'ta/',
            'home-te' => 'te/',
            'home-th' => 'th/',
            'home-tr' => 'tr/',
            'home-ur' => 'ur/',
            'home-vi' => 'vi/',
            'home-yo' => 'yo/',
            'home-zhcn' => 'zhcn/',
            'home-zhhk' => 'zhhk/',
            'home-zhtw' => 'zhtw/',

            'login-am' => 'am/login',
            'login-ar_jo' => 'ar_jo/login',
            'login-ar' => 'ar/login',
            'login-asl' => 'asl/login',
            'login-bho' => 'bho/login',
            'login-bn' => 'bn/login',
            'login-bs' => 'bs/login',
            'login-de' => 'de/login',
            'login-es' => 'es/login',
            'login-fa' => 'fa/login',
            'login-fr' => 'fr/login',
            'login-gu' => 'gu/login',
            'login-ha' => 'ha/login',
            'login-hi' => 'hi/login',
            'login-hr' => 'hr/login',
            'login-in' => 'in/login',
            'login-it' => 'it/login',
            'login-ja' => 'ja/login',
            'login-kn' => 'kn/login',
            'login-ko' => 'ko/login',
            'login-ku' => 'ku/login',
            'login-lo' => 'lo/login',
            'login-mai' => 'mai/login',
            'login-ml' => 'ml/login',
            'login-mr' => 'mr/login',
            'login-or' => 'or/login',
            'login-pa' => 'pa/login',
            'login-pt' => 'pt/login',
            'login-ro' => 'ro/login',
            'login-ru' => 'ru/login',
            'login-sl' => 'sl/login',
            'login-so' => 'so/login',
            'login-sw' => 'sw/login',
            'login-ta' => 'ta/login',
            'login-te' => 'te/login',
            'login-th' => 'th/login',
            'login-tr' => 'tr/login',
            'login-ur' => 'ur/login',
            'login-vi' => 'vi/login',
            'login-yo' => 'yo/login',
            'login-zhcn' => 'zhcn/login',
            'login-zhhk' => 'zhhk/login',
            'login-zhtw' => 'zhtw/login',

            'privacy-policy-am' => 'am/privacy',
            'am/privacy-policy' => '/am/privacy',
            'privacy-policy-ar_jo' => 'ar_jo/privacy',
            'privacy-policy-ar' => 'ar/privacy',
            'privacy-policy-asl' => 'asl/privacy',
            'privacy-policy-bho' => 'bho/privacy',
            'privacy-policy-bn' => 'bn/privacy',
            'privacy-policy-bs' => 'bs/privacy',
            'privacy-policy-de' => 'de/privacy',
            'privacy-policy-es' => 'es/privacy',
            'privacy-policy-fa' => 'fa/privacy',
            'privacy-policy-fr' => 'fr/privacy',
            'privacy-policy-gu' => 'gu/privacy',
            'privacy-policy-ha' => 'ha/privacy',
            'privacy-policy-hi' => 'hi/privacy',
            'privacy-policy-hr' => 'hr/privacy',
            'privacy-policy-in' => 'in/privacy',
            'privacy-policy-it' => 'it/privacy',
            'privacy-policy-ja' => 'ja/privacy',
            'privacy-policy-kn' => 'kn/privacy',
            'privacy-policy-ko' => 'ko/privacy',
            'privacy-policy-ku' => 'ku/privacy',
            'privacy-policy-lo' => 'lo/privacy',
            'privacy-policy-mai' => 'mai/privacy',
            'privacy-policy-ml' => 'ml/privacy',
            'privacy-policy-mr' => 'mr/privacy',
            'privacy-policy-or' => 'or/privacy',
            'privacy-policy-pa' => 'pa/privacy',
            'privacy-policy-pt' => 'pt/privacy',
            'privacy-policy-ro' => 'ro/privacy',
            'privacy-policy-ru' => 'ru/privacy',
            'privacy-policy-sl' => 'sl/privacy',
            'privacy-policy-so' => 'so/privacy',
            'privacy-policy-sw' => 'sw/privacy',
            'privacy-policy-ta' => 'ta/privacy',
            'privacy-policy-te' => 'te/privacy',
            'privacy-policy-th' => 'th/privacy',
            'privacy-policy-tr' => 'tr/privacy',
            'privacy-policy-ur' => 'ur/privacy',
            'privacy-policy-vi' => 'vi/privacy',
            'privacy-policy-yo' => 'yo/privacy',
            'privacy-policy-zhcn' => 'zhcn/privacy',
            'privacy-policy-zhhk' => 'zhhk/privacy',
            'privacy-policy-zhtw' => 'zhtw/privacy',
            'privacy-policy' => '/privacy',


            'overview-am' => 'am/training',
            'overview-ar' => 'ar/training',
            'overview-bn' => 'bn/training',
            'overview-es' => 'es/training',
            'overview-fa' => 'fa/training',
            'overview-fr' => 'fr/training',
            'overview-hi' => 'hi/training',
            'overview-in' => 'in/training',
            'overview-it' => 'it/training',
            'overview-ku' => 'ku/training',
            'overview-mr' => 'mr/training',
            'overview-or' => 'or/training',
            'overview-so' => 'so/training',
            'overview-sw' => 'sw/training',
            'overview-ta' => 'ta/training',
            'overview-te' => 'te/training',
            'overview-th' => 'th/training',
            'overview-zhcn' => 'zhcn/training',
            'overview-zhtw' => 'zhtw/training',
            'overview' => 'training',


            'profile-am' => 'am/dashboard',
            'profile-ar_jo' => 'ar_jo/dashboard',
            'profile-ar' => 'ar/dashboard',
            'profile-asl' => 'asl/dashboard',
            'profile-bho' => 'bho/dashboard',
            'profile-bn' => 'bn/dashboard',
            'profile-bs' => 'bs/dashboard',
            'profile-de' => 'de/dashboard',
            'profile-es' => 'es/dashboard',
            'profile-fa' => 'fa/dashboard',
            'profile-fr' => 'fr/dashboard',
            'profile-gu' => 'gu/dashboard',
            'profile-ha' => 'ha/dashboard',
            'profile-hi' => 'hi/dashboard',
            'profile-hr' => 'hr/dashboard',
            'profile-in' => 'in/dashboard',
            'profile-it' => 'it/dashboard',
            'profile-ja' => 'ja/dashboard',
            'profile-kn' => 'kn/dashboard',
            'profile-ko' => 'ko/dashboard',
            'profile-ku' => 'ku/dashboard',
            'profile-lo' => 'lo/dashboard',
            'profile-mai' => 'mai/dashboard',
            'profile-ml' => 'ml/dashboard',
            'profile-mr' => 'mr/dashboard',
            'profile-ne' => 'ne/dashboard',
            'profile-or' => 'or/dashboard',
            'profile-pa' => 'pa/dashboard',
            'profile-pt' => 'pt/dashboard',
            'profile-ro' => 'ro/dashboard',
            'profile-ru' => 'ru/dashboard',
            'profile-sl' => 'sl/dashboard',
            'profile-so' => 'so/dashboard',
            'profile-sw' => 'sw/dashboard',
            'profile-ta' => 'ta/dashboard',
            'profile-te' => 'te/dashboard',
            'profile-th' => 'th/dashboard',
            'profile-tr' => 'tr/dashboard',
            'profile-ur' => 'ur/dashboard',
            'profile-vi' => 'vi/dashboard',
            'profile-yo' => 'yo/dashboard',
            'profile-zhcn' => 'zhcn/dashboard',
            'profile-zhhk' => 'zhhk/dashboard',
            'profile-zhtw' => 'zhtw/dashboard',

            'progress-ar' => 'ar/training',
            'progress-bn' => 'bn/training',
            'progress-es' => 'es/training',
            'progress-fa' => 'fa/training',
            'progress-fr' => 'fr/training',
            'progress-hi' => 'hi/training',
            'progress-in' => 'in/training',
            'progress-it' => 'it/training',
            'progress-mr' => 'mr/training',
            'progress-or' => 'or/training',
            'progress-so' => 'so/training',
            'progress-sw' => 'sw/training',
            'progress-ta' => 'ta/training',
            'progress-te' => 'te/training',
            'progress-th' => 'th/training',

            'three-month-plan-am' => 'am/dashboard',
            'three-month-plan-ar_jo' => 'ar_jo/dashboard',
            'three-month-plan-ar' => 'ar/dashboard',
            'three-month-plan-asl' => 'asl/dashboard',
            'three-month-plan-bho' => 'bho/dashboard',
            'three-month-plan-bn' => 'bn/dashboard',
            'three-month-plan-bs' => 'bs/dashboard',
            'three-month-plan-de' => 'de/dashboard',
            'three-month-plan-es' => 'es/dashboard',
            'three-month-plan-fa' => 'fa/dashboard',
            'three-month-plan-fr' => 'fr/dashboard',
            'three-month-plan-gu' => 'gu/dashboard',
            'three-month-plan-ha' => 'ha/dashboard',
            'three-month-plan-hi' => 'hi/dashboard',
            'three-month-plan-hr' => 'hr/dashboard',
            'three-month-plan-in' => 'in/dashboard',
            'three-month-plan-it' => 'it/dashboard',
            'three-month-plan-ja' => 'ja/dashboard',
            'three-month-plan-kn' => 'kn/dashboard',
            'three-month-plan-ko' => 'ko/dashboard',
            'three-month-plan-ku' => 'ku/dashboard',
            'three-month-plan-lo' => 'lo/dashboard',
            'three-month-plan-mai' => 'mai/dashboard',
            'three-month-plan-ml' => 'ml/dashboard',
            'three-month-plan-mr' => 'mr/dashboard',
            'three-months-plan-ne' => 'ne/dashboard',
            'three-month-plan-or' => 'or/dashboard',
            'three-month-plan-pa' => 'pa/dashboard',
            'three-month-plan-pt' => 'pt/dashboard',
            'three-month-plan-ro' => 'ro/dashboard',
            'three-month-plan-ru' => 'ru/dashboard',
            'three-month-plan-sl' => 'sl/dashboard',
            'three-month-plan-so' => 'so/dashboard',
            'three-month-plan-sw' => 'sw/dashboard',
            'three-month-plan-ta' => 'ta/dashboard',
            'three-month-plan-te' => 'te/dashboard',
            'three-month-plan-th' => 'th/dashboard',
            'three-month-plan-tr' => 'tr/dashboard',
            'three-month-plan-ur' => 'ur/dashboard',
            'three-month-plan-vi' => 'vi/dashboard',
            'three-month-plan-yo' => 'yo/dashboard',
            'three-month-plan-zhcn' => 'zhcn/dashboard',
            'three-month-plan-zhhk' => 'zhhk/dashboard',
            'three-month-plan-zhtw' => 'zhtw/dashboard',
            'three-month-plan' => '/dashboard',

            'resource-ja' => 'ja/resource',
            'resource-ta' => 'ta/resource',
            'resources-am' => 'am/resource',
            'resources-ar_jo' => 'ar_jo/resource',
            'resources-ar' => 'ar/resource',
            'resources-asl' => 'asl/resource',
            'resources-bho' => 'bho/resource',
            'resources-bn' => 'bn/resource',
            'resources-bs' => 'bs/resource',
            'resources-de' => 'de/resource',
            'resources-es' => 'es/resource',
            'resources-fa' => 'fa/resource',
            'resources-fr' => 'fr/resource',
            'resources-gu' => 'gu/resource',
            'resources-ha' => 'ha/resource',
            'resources-hi' => 'hi/resource',
            'resources-hr' => 'hr/resource',
            'resources-in' => 'in/resource',
            'resources-it' => 'it/resource',
            'resources-kn' => 'kn/resource',
            'resources-ko' => 'ko/resource',
            'resources-ku' => 'ku/resource',
            'resources-lo' => 'lo/resource',
            'resources-mai' => 'mai/resource',
            'resources-ml' => 'ml/resource',
            'resources-mr' => 'mr/resource',
            'resources-or' => 'or/resource',
            'resources-pa' => 'pa/resource',
            'resources-pt' => 'pt/resource',
            'resources-ro' => 'ro/resource',
            'resources-ru' => 'ru/resource',
            'resources-sl' => 'sl/resource',
            'resources-so' => 'so/resource',
            'resources-sw' => 'sw/resource',
            'resources-te' => 'te/resource',
            'resources-th' => 'th/resource',
            'resources-tr' => 'tr/resource',
            'resources-ur' => 'ur/resource',
            'resources-vi' => 'vi/resource',
            'resources-yo' => 'yo/resource',
            'resources-zhcn' => 'zhcn/resource',
            'resources-zhhk' => 'zhhk/resource',
            'resources-zhtw' => 'zhtw/resource',


            'training-am' => 'am/training',
            'training-ar_jo' => 'ar_jo/training',
            'training-ar' => 'ar/training',
            'training-asl' => 'asl/training',
            'training-bho' => 'bho/training',
            'training-bn' => 'bn/training',
            'training-bs' => 'bs/training',
            'training-cycle-for-maturing-disciples-am' => '',
            'training-de' => 'de/training',
            'training-es' => 'es/training',
            'training-fa' => 'fa/training',
            'training-fr' => 'fr/training',
            'training-gu' => 'gu/training',
            'training-ha' => 'ha/training',
            'training-hi' => 'hi/training',
            'training-hr' => 'hr/training',
            'training-id' => 'id/training',
            'training-it' => 'it/training',
            'training-ja' => 'ja/training',
            'training-kn' => 'kn/training',
            'training-ko' => 'ko/training',
            'training-ku' => 'ku/training',
            'training-lo' => 'lo/training',
            'training-mai' => 'mai/training',
            'training-ml' => 'ml/training',
            'training-mr' => 'mr/training',
            'training-ne' => 'ne/training',
            'training-or' => 'or/training',
            'training-pa' => 'pa/training',
            'training-pt' => 'pt/training',
            'training-ro' => 'ro/training',
            'training-ru' => 'ru/training',
            'training-sl' => 'sl/training',
            'training-so' => 'so/training',
            'training-swa' => 'swa/training',
            'training-ta' => 'ta/training',
            'training-te' => 'te/training',
            'training-th' => 'th/training',
            'training-tr' => 'tr/training',
            'training-ur' => 'ur/training',
            'training-vi' => 'vi/training',
            'training-yo' => 'yo/training',
            'training-zhcn' => 'zhcn/training',
            'training-zhhk' => 'zhhk/training',
            'training-zhtw' => 'zhtw/training',


            'translation-bho' => 'bho/translation',
            'translation-kn' => 'kn/translation',
            'translation-progress-am' => 'am/translation-progress',
            'translation-progress-asl' => 'asl/translation-progress',
            'translation-progress-ha' => 'ha/translation-progress',
            'translation-progress-hr' => 'hr/translation-progress',
            'translation-progress-ja' => 'ja/translation-progress',
            'translation-progress-ku' => 'ku/translation-progress',
            'translation-progress-mai' => 'mai/translation-progress',
            'translation-progress-ro' => 'ro/translation-progress',
            'translation-progress-sl' => 'sl/translation-progress',
            'translation-progress-tr' => 'tr/translation-progress',


        ];
        return $pages;



    }

    public function redirect( $redirect ) {
        header( 'Location: '.$redirect, true, 302 );
        exit();
    }
}
Zume_301_Redirects::instance();
